import 'package:flutter/material.dart';
import '../../services/picking_service.dart';
import '../common_widgets.dart';

class AdminPickingScreen extends StatefulWidget {
  const AdminPickingScreen({super.key});
  @override State<AdminPickingScreen> createState()=>_AdminPickingScreenState();
}
class _AdminPickingScreenState extends State<AdminPickingScreen>{
  final api=PickingService.instance;
  List<Map<String,dynamic>> tasks=[];
  bool loading=true;
  String? error;
  @override void initState(){super.initState();load();}
  Future<void> load()async{setState(()=>loading=true);try{final x=await api.tasks();if(mounted)setState(()=>tasks=x);}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>loading=false);}}
  void msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
  Future<void> createTask()async{try{final orders=await api.pending();if(!mounted)return;if(orders.isEmpty){msg('No allocated/picking orders available.');return;}final id=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('Select Order'),content:SizedBox(width:650,height:400,child:ListView.builder(itemCount:orders.length,itemBuilder:(c,i){final o=orders[i];return ListTile(title:Text((o['order_no']??'') .toString()+' • '+(o['client_name']??'').toString()),subtitle:Text((o['warehouse_name']??'').toString()+' • Remaining '+(o['remaining_qty']??0).toString()),onTap:()=>Navigator.pop(c,o['id'].toString()));})))));if(id==null)return;await api.createTask(id);msg('Picking task created.');load();}catch(e){msg(e.toString());}}
  Future<void> open(Map<String,dynamic> t)async{try{final d=await api.detail(t['id'].toString());if(!mounted)return;await showDialog(context:context,builder:(_)=>_Detail(detail:d,api:api));load();}catch(e){msg(e.toString());}}
  @override Widget build(BuildContext context)=>ScreenFrame(title:'Picking',subtitle:'Production picking with location-wise stock control.',actions:[OutlinedButton.icon(onPressed:load,icon:const Icon(Icons.refresh),label:const Text('Refresh')),const SizedBox(width:8),FilledButton.icon(onPressed:createTask,icon:const Icon(Icons.add_task),label:const Text('Create Pick Task'))],child:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!,style:const TextStyle(color:Colors.red)),OutlinedButton(onPressed:load,child:const Text('Retry'))])):tasks.isEmpty?const Center(child:Text('No picking tasks.')):HorizontalTableScroller(child:DataTable(columns:const[DataColumn(label:Text('Pick Task')),DataColumn(label:Text('Order')),DataColumn(label:Text('Client')),DataColumn(label:Text('Warehouse')),DataColumn(label:Text('Picker')),DataColumn(label:Text('Picked')),DataColumn(label:Text('Status')),DataColumn(label:Text('Action'))],rows:tasks.map((t)=>DataRow(cells:[DataCell(Text(t['id'].toString().substring(0,8).toUpperCase())),DataCell(Text((t['order_no']??'-').toString())),DataCell(Text((t['client_name']??'-').toString())),DataCell(Text((t['warehouse_name']??'-').toString())),DataCell(Text((t['picker_name']??'-').toString())),DataCell(Text((t['picked_qty']??0).toString())),DataCell(Text((t['status']??'-').toString())),DataCell(IconButton(icon:const Icon(Icons.visibility_outlined),onPressed:()=>open(t)))] )).toList())));
}
class _Detail extends StatefulWidget{final Map<String,dynamic> detail;final PickingService api;const _Detail({required this.detail,required this.api});@override State<_Detail> createState()=>_DetailState();}
class _DetailState extends State<_Detail>{
 bool busy=false;
 void msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 Future<void> pick(Map<String,dynamic> item)async{final plan=(widget.detail['pickPlan'] as List???[]).map((e)=>Map<String,dynamic>.from(e)).where((e)=>e['orderItemId']==item['order_item_id']).toList();if(plan.isEmpty){msg('No available stock locations.');return;}final p=await showDialog<Map<String,dynamic>>(context:context,builder:(_)=>_Pick(item:item,plan:plan));if(p==null)return;try{setState(()=>busy=true);await widget.api.pick(widget.detail['task']['id'].toString(),orderItemId:item['order_item_id'].toString(),locationId:p['locationId'].toString(),quantity:p['quantity'] as double);if(mounted)Navigator.pop(context);}catch(e){msg(e.toString());}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> complete()async{try{setState(()=>busy=true);await widget.api.complete(widget.detail['task']['id'].toString());if(mounted)Navigator.pop(context);}catch(e){msg(e.toString());}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context){final t=Map<String,dynamic>.from(widget.detail['task'] as Map);final items=(widget.detail['items'] as List???[]).map((e)=>Map<String,dynamic>.from(e)).toList();return AlertDialog(title:Text((t['order_no']??'').toString()+' • '+(t['warehouse_name']??'').toString()),content:SizedBox(width:900,height:560,child:ListView.separated(itemCount:items.length,separatorBuilder:(_,__)=>const Divider(),itemBuilder:(c,i){final x=items[i];final rem=double.tryParse((x['remaining_qty']??0).toString())??0;return ListTile(title:Text((x['product_name']??'').toString()+' • '+(x['sku']??'').toString()),subtitle:Text('Ordered '+(x['ordered_qty']??0).toString()+' | Picked '+(x['picked_qty']??0).toString()+' | Remaining '+rem.toString()),trailing:rem>0?FilledButton(onPressed:busy?null:()=>pick(x),child:const Text('Pick')):const Icon(Icons.check_circle,color:Colors.green));})),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close')),FilledButton(onPressed:busy?null:complete,child:const Text('Complete Picking'))]);}
}
class _Pick extends StatefulWidget{final Map<String,dynamic> item;final List<Map<String,dynamic>> plan;const _Pick({required this.item,required this.plan});@override State<_Pick> createState()=>_PickState();}
class _PickState extends State<_Pick>{late Map<String,dynamic> selected;late TextEditingController qty;@override void initState(){super.initState();selected=widget.plan.first;qty=TextEditingController(text:selected['suggestedPickQuantity'].toString());}@override void dispose(){qty.dispose();super.dispose();}@override Widget build(BuildContext context)=>AlertDialog(title:Text('Pick '+(widget.item['product_name']??'').toString()),content:SizedBox(width:600,child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<Map<String,dynamic>>(value:selected,decoration:const InputDecoration(labelText:'Location',border:OutlineInputBorder()),items:widget.plan.map((p)=>DropdownMenuItem(value:p,child:Text((p['locationCode']??'').toString()+' • Available '+p['availableQuantity'].toString()+' • Suggested '+p['suggestedPickQuantity'].toString()))).toList(),onChanged:(v){if(v!=null)setState(()=>selected=v);}),const SizedBox(height:10),TextField(controller:qty,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Pick Quantity',border:OutlineInputBorder()))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,{'locationId':selected['locationId'],'quantity':double.tryParse(qty.text)??0}),child:const Text('Confirm Pick'))]);}
