import 'package:flutter/material.dart';
import '../../services/putaway_service.dart';
import '../common_widgets.dart';

class AdminPutawayScreen extends StatefulWidget {
  const AdminPutawayScreen({super.key});
  @override State<AdminPutawayScreen> createState()=>_AdminPutawayScreenState();
}
class _AdminPutawayScreenState extends State<AdminPutawayScreen>{
  final api=PutawayService.instance; List<Map<String,dynamic>> tasks=[],pending=[]; String status='All'; bool loading=true;
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{setState(()=>loading=true);try{tasks=await api.tasks();pending=await api.pending();if(mounted)setState(()=>loading=false);}catch(e){if(mounted){setState(()=>loading=false);_msg(e.toString().replaceFirst('Exception: ',''));}}}
  String _source(Map<String,dynamic> t)=>t['reference_no']?.toString()??'-'; String _stat(Map<String,dynamic> t)=>t['status']?.toString()??'-';
  @override Widget build(BuildContext context)=>ScreenFrame(title:'PUT / Putaway',subtitle:'Move QC-approved material from staging to warehouse locations.',actions:[FilledButton.icon(onPressed:_create,icon:const Icon(Icons.add),label:const Text('Create PUT')),IconButton(onPressed:_load,icon:const Icon(Icons.refresh))],child:loading?const Center(child:CircularProgressIndicator()):Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_summary(),const SizedBox(height:16),_pending(),const SizedBox(height:16),_history()]));
  Widget _summary()=>Wrap(spacing:12,runSpacing:12,children:[_card('Pending Source Items',pending.length,Icons.pending_actions_outlined),_card('PUT Tasks',tasks.length,Icons.inventory_2_outlined),_card('In Progress',tasks.where((x)=>_stat(x)=='in_progress').length,Icons.sync_outlined),_card('Completed',tasks.where((x)=>_stat(x)=='completed').length,Icons.check_circle_outline)]);
  Widget _card(String t,int n,IconData i)=>Container(width:210,padding:const EdgeInsets.all(15),decoration:_box(),child:Row(children:[Icon(i,color:const Color(0xFF1769E8),size:28),const SizedBox(width:12),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700)),Text(n.toString(),style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900))])]));
  Widget _pending()=>_panel('QC Approved Material — Ready for Putaway',pending.isEmpty?const Padding(padding:EdgeInsets.all(18),child:Text('No QC-approved material is waiting for putaway.')):HorizontalTableScroller(child:DataTable(columns:const[DataColumn(label:Text('Source')),DataColumn(label:Text('Product / SKU')),DataColumn(label:Text('Accepted')),DataColumn(label:Text('Putaway')),DataColumn(label:Text('Warehouse')),DataColumn(label:Text('Action'))],rows:pending.map((p)=>DataRow(cells:[DataCell(Text(_source(p))),DataCell(Text((p['product_name']??'-').toString()+' / '+(p['sku']??'-').toString())),DataCell(Text(p['accepted_qty'].toString())),DataCell(Text(p['putaway_qty'].toString())),DataCell(Text((p['warehouse_code']??'-').toString())),DataCell(FilledButton(onPressed:()=>_create(source:p),child:const Text('Create PUT')))])).toList()));
  Widget _history()=>_panel('Putaway History',Column(children:[DropdownButton<String>(value:status,items:const['All','pending','in_progress','completed','cancelled'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>status=v??'All')),const Divider(),HorizontalTableScroller(child:DataTable(columns:const[DataColumn(label:Text('PUT No.')),DataColumn(label:Text('Source')),DataColumn(label:Text('Product')),DataColumn(label:Text('Qty')),DataColumn(label:Text('Warehouse')),DataColumn(label:Text('Location')),DataColumn(label:Text('Status')),DataColumn(label:Text('Action'))],rows:tasks.where((t)=>status=='All'||_stat(t)==status).map((t)=>DataRow(cells:[DataCell(Text(t['putaway_no']?.toString()??'-')),DataCell(Text(_source(t))),DataCell(Text((t['product_name']??'-').toString())),DataCell(Text(t['quantity'].toString())),DataCell(Text((t['warehouse_code']??'-').toString())),DataCell(Text((t['location_code']??'-').toString())),DataCell(Text(_stat(t))),DataCell(t['status']=='completed'?const Icon(Icons.check_circle,color:Colors.green):IconButton(onPressed:()=>_process(t),icon:const Icon(Icons.play_arrow,color:Color(0xFF1769E8))))])).toList()))]));
  Widget _panel(String title,Widget child)=>Container(padding:const EdgeInsets.all(14),decoration:_box(),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w800,color:Color(0xFF162B46))),const SizedBox(height:10),child]));
  BoxDecoration _box()=>BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(12),border:Border.all(color:const Color(0xFFE1E8F1)));
  Future<void> _create({Map<String,dynamic>? source})async{
    final p=source??(pending.isNotEmpty?pending.first:null); if(p==null){_msg('No QC-approved material available.');return;}
    List<Map<String,dynamic>> locs=[]; try{locs=await api.locations(p['warehouse_id'].toString());}catch(e){_msg(e.toString().replaceFirst('Exception: ',''));return;} if(locs.isEmpty){_msg('No active location found in this warehouse.');return;}
    String loc=locs.first['id'].toString(); final remaining=double.parse(p['accepted_qty'].toString())-double.parse(p['putaway_qty'].toString()); final qty=TextEditingController(text:remaining.toStringAsFixed(3));
    await showDialog(context:context,builder:(ctx)=>AlertDialog(title:Text('Create PUT — '+_source(p)),content:SizedBox(width:430,child:Column(mainAxisSize:MainAxisSize.min,children:[Text((p['product_name']??'-').toString()+' ('+(p['sku']??'-').toString()+')'),const SizedBox(height:12),TextField(controller:qty,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Quantity')),const SizedBox(height:10),DropdownButtonFormField<String>(value:loc,decoration:const InputDecoration(labelText:'Destination Location'),items:locs.map((x)=>DropdownMenuItem(value:x['id'].toString(),child:Text((x['code']??'').toString()+' • '+(x['zone']??'').toString()+' '+(x['bin']??'').toString()))).toList(),onChanged:(v)=>loc=v??loc)])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()async{try{await api.create(sourceType:p['source_type'].toString(),sourceItemId:p['source_item_id'].toString(),locationId:loc,quantity:double.parse(qty.text));if(ctx.mounted)Navigator.pop(ctx);await _load();_msg('PUT created successfully.');}catch(e){_msg(e.toString().replaceFirst('Exception: ',''));}},child:const Text('Create PUT'))]));
  }
  Future<void> _process(Map<String,dynamic> t)async{try{await api.process(t['id'].toString(),t['location_id'].toString());await _load();_msg('Putaway completed and inventory updated.');}catch(e){_msg(e.toString().replaceFirst('Exception: ',''));}}
  void _msg(String m)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(m)));
}
