import 'package:flutter/material.dart';
import '../../services/stock_transfer_service.dart';
import '../common_widgets.dart';

class AdminStockTransferScreen extends StatefulWidget{const AdminStockTransferScreen({super.key});@override State<AdminStockTransferScreen> createState()=>_AdminStockTransferScreenState();}
class _AdminStockTransferScreenState extends State<AdminStockTransferScreen>{
 final api=StockTransferService.instance;List<Map<String,dynamic>> rows=[];bool loading=true;String? error;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{setState(()=>loading=true);try{rows=await api.list();error=null;}catch(e){error=e.toString().replaceFirst('Exception: ','');}if(mounted)setState(()=>loading=false);}
 @override Widget build(BuildContext c)=>ScreenFrame(title:'Stock Transfer / STO',subtitle:'Controlled movement of stock between warehouses with approval, picking and receiving.',actions:[OutlinedButton.icon(onPressed:loading?null:_load,icon:const Icon(Icons.refresh),label:const Text('Refresh')),const SizedBox(width:8),FilledButton.icon(onPressed:_newSto,icon:const Icon(Icons.add),label:const Text('New STO'))],child:loading?const Center(child:CircularProgressIndicator()):error!=null?_err():Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_cards(),const SizedBox(height:16),_panel()]);
 Widget _cards()=>Wrap(spacing:12,runSpacing:12,children:[_card('Total',rows.length),_card('Pending Approval',rows.where((x)=>x['status']=='pending_approval').length),_card('In Transit',rows.where((x)=>x['status']=='in_transit').length),_card('Received',rows.where((x)=>x['status']=='received').length)]);
 Widget _card(String t,num n)=>Container(width:190,padding:const EdgeInsets.all(15),decoration:_box(),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700)),const SizedBox(height:5),Text(n.toString(),style:const TextStyle(fontSize:23,fontWeight:FontWeight.w900))]));
 Widget _panel()=>Container(padding:const EdgeInsets.all(14),decoration:_box(),child:HorizontalTableScroller(child:DataTable(columns:const[DataColumn(label:Text('STO No.')),DataColumn(label:Text('Source')),DataColumn(label:Text('Destination')),DataColumn(label:Text('Status')),DataColumn(label:Text('Created')),DataColumn(label:Text('Action'))],rows:rows.map((x)=>DataRow(cells:[DataCell(Text(x['sto_no']?.toString()??'-')),DataCell(Text(x['source_warehouse_code']?.toString()??'-')),DataCell(Text(x['destination_warehouse_code']?.toString()??'-')),DataCell(Text(x['status']?.toString()??'-')),DataCell(Text(x['created_at']?.toString().replaceFirst('T',' ')??'-')),DataCell(x['status']=='pending_approval'?FilledButton(onPressed:()=>_approve(x),child:const Text('Approve')):const Text('—'))])).toList())));
 Future<void> _approve(Map<String,dynamic> x)async{try{await api.approve(x['id'].toString());await _load();_msg('STO approved.');}catch(e){_msg(e.toString().replaceFirst('Exception: ',''));}}
 Future<void> _newSto()async{final no=TextEditingController(text:'STO-'+DateTime.now().millisecondsSinceEpoch.toString());final src=TextEditingController();final dst=TextEditingController();final product=TextEditingController();final qty=TextEditingController(text:'1');await showDialog(context:context,builder:(ctx)=>AlertDialog(title:const Text('Create Stock Transfer'),content:SizedBox(width:500,child:Column(mainAxisSize:MainAxisSize.min,children:[_field(no,'STO No.'),_field(src,'Source Warehouse ID'),_field(dst,'Destination Warehouse ID'),_field(product,'Product ID'),_field(qty,'Requested Quantity')])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()async{try{await api.create(stoNo:no.text.trim(),sourceWarehouseId:src.text.trim(),destinationWarehouseId:dst.text.trim(),items:[{'productId':product.text.trim(),'requestedQty':double.parse(qty.text)}]);if(ctx.mounted)Navigator.pop(ctx);await _load();_msg('STO created.');}catch(e){_msg(e.toString().replaceFirst('Exception: ',''));}},child:const Text('Create'))]));}
 Widget _field(TextEditingController c,String label)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
 BoxDecoration _box()=>BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(12),border:Border.all(color:const Color(0xFFE1E8F1)));
 Widget _err()=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!),const SizedBox(height:10),FilledButton(onPressed:_load,child:const Text('Retry'))]));
 void _msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
}